#if !canImport(ObjectiveC)
    import XCTest

    extension LoggerTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__LoggerTests = [
            ("testArgumentsWithoutLoggingOptions", testArgumentsWithoutLoggingOptions),
            ("testChannelComparison", testChannelComparison),
            ("testChannelComplexName", testChannelComplexName),
            ("testChannelSimpleName", testChannelSimpleName),
            ("testContextDescription", testContextDescription),
            ("testDebugLogging", testDebugLogging),
            ("testEnabledViaSettings", testEnabledViaSettings),
            ("testFatalError", testFatalError),
            ("testHandlerComparison", testHandlerComparison),
            ("testLoggingDisabled", testLoggingDisabled),
            ("testLoggingEnabled", testLoggingEnabled),
            ("testSettings", testSettings),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(LoggerTests.__allTests__LoggerTests),
        ]
    }
#endif
