#if !canImport(ObjectiveC)
import XCTest

extension LoggerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LoggerTests = [
        ("testArgumentsWithoutLoggingOptions", testArgumentsWithoutLoggingOptions),
        ("testContextDescription", testContextDescription),
        ("testDebugLogging", testDebugLogging),
        ("testEnabledViaSettings", testEnabledViaSettings),
        ("testFatalError", testFatalError),
        ("testHandlerComparison", testHandlerComparison),
        ("testLoggerComparison", testLoggerComparison),
        ("testLoggerComplexName", testLoggerComplexName),
        ("testLoggerSimpleName", testLoggerSimpleName),
        ("testLoggingDisabled", testLoggingDisabled),
        ("testLoggingEnabled", testLoggingEnabled),
        ("testSettings", testSettings),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LoggerTests.__allTests__LoggerTests),
    ]
}
#endif
